Repository career-seekers/career-seekers-front, pull requests merged in 2025-09, with the labels that each got.

#34 Fix/rename docs aliases
  src/views/expert/ExpertDashboardHome.vue
  src/views/tutor/TutorDocuments.vue
Labels: bug

#39 Refactor/multi age choise
  src/api/resolvers/competence/dto/input/competence-input.dto.ts
  src/api/resolvers/competence/dto/output/age-category-output.dto.ts
  src/api/resolvers/competence/dto/output/competence-output.dto.ts
  src/views/tutor/TutorCompetencies.vue
Labels: enhancement

#41 Fix/update expert registration
  src/api/resolvers/expertDocuments/dto/input/expert-docs.input.dto.ts
  src/api/resolvers/expertDocuments/dto/output/expert-docs.output.dto.ts
  src/api/resolvers/expertDocuments/expert-documents.resolver.ts
  src/api/resolvers/user/dto/input/user-input.dto.ts
  src/api/resolvers/user/dto/output/user-output-expert-docs.dto.ts
  src/api/resolvers/user/dto/output/user-output.dto.ts
  src/views/tutor/TutorExperts.vue
Labels: enhancement

#47 Fix | Admin panel | Edit tutors & experts info
  src/api/resolvers/tutorDocuments/dto/input/tutor-docs-input.dto.ts
  src/api/resolvers/tutorDocuments/dto/input/tutor-update-docs-input.dto.ts
  src/api/resolvers/tutorDocuments/tutor-documents.resolver.ts
  src/state/UserState.ts
  src/utils/ApiResolver.ts
  src/views/admin/AdminCompetencies.vue
  src/views/admin/AdminExperts.vue
  src/views/admin/AdminTutors.vue
  src/views/tutor/TutorExperts.vue
  tsconfig.tsbuildinfo
Labels: enhancement

#51 Fix | Routes |: block unpublished routes to be visited
  src/router/index.ts
  src/state/UserState.ts
  src/utils/JwtManager.ts
  src/views/auth/EmailConfirmationView.vue
Labels: bug, ready for merge

#52 fix(auth): convert all emails to lowercase
  src/views/auth/LoginView.vue
  src/views/auth/MentorRegisterView.vue
  src/views/auth/ParentRegisterView.vue
  src/views/auth/TutorRegisterView.vue
Labels: bug, ready for merge

#69 Feat | Display document's age category
  src/components/DocumentsTemplates.vue
  src/shared/UseAgeGroups.ts
  src/shared/UseDocumentTemplates.ts
  src/shared/UseDocumentTypes.ts
  src/views/admin/AdminCompetencies.vue
  src/views/admin/AdminDocuments.vue
  src/views/expert/ExpertCompetencies.vue
  src/views/expert/ExpertDashboardHome.vue
  src/views/shared/CompetenceDocuments.vue
  src/views/tutor/TutorCompetencies.vue
  src/views/tutor/TutorDocuments.vue
  tsconfig.tsbuildinfo
Labels: enhancement

#72 Fix | Doc verify
  src/components/DocsToVerifyList.vue
  src/views/admin/AdminDocuments.vue
Labels: enhancement

#75 Refactor | Unifed dashboard
  src/App.vue
  src/router/index.ts
  src/views/expert/ExpertDashboard.vue
  src/views/mentor/MentorDashboard.vue
  src/views/parent/ParentDashboard.vue
  src/views/shared/DashboardWrapper.vue
  src/views/tutor/TutorDashboard.vue
  tsconfig.tsbuildinfo
Labels: enhancement

#83 Fix/expert docs fix
  src/views/shared/CompetenceDocuments.vue
Labels: bug, ready for merge

#85 feat(auth): password reset page added
  src/api/resolvers/auth/auth.resolver.ts
  src/api/resolvers/auth/dto/input/forgot-password-input.dto.ts
  src/components/ToastPopup.vue
  src/router/index.ts
  src/views/auth/ForgotPasswordView.vue
  src/views/auth/LoginView.vue
Labels: enhancement, ready for merge

#84 Refactor | parent personal account
  src/App.vue
  src/api/resolvers/child/child.resolver.ts
  src/api/resolvers/child/dto/input/child-input.dto.ts
  src/api/resolvers/child/dto/input/child-update-input.dto.ts
  src/api/resolvers/child/dto/output/child-output.dto.ts
  src/api/resolvers/childDocuments/child-documents.resolver.ts
  src/api/resolvers/childDocuments/dto/input/child-documents-input.dto.ts
  src/api/resolvers/childDocuments/dto/input/child-documents-update-input.dto.ts
  src/api/resolvers/childDocuments/dto/output/child-documents-output.dto.ts
  src/api/resolvers/files/file.resolver.ts
  src/api/resolvers/platform/platform.resolver.ts
  src/api/resolvers/user/dto/output/user-output.dto.ts
  src/api/resolvers/userDocuments/dto/output/user-docs-output.dto.ts
  src/api/resolvers/userDocuments/user-documents.resolver.ts
  src/components/AddChildForm.vue
  src/components/ChildrenList.vue
  src/router/index.ts
  src/shared/UseGradeOptions.ts
  src/state/UserState.types.ts
  src/stores/authStore.ts
  src/stores/userStore.ts
  src/utils/RouterGuardManager.ts
  src/views/auth/EmailConfirmationView.vue
  src/views/auth/LoginView.vue
  src/views/auth/UserRegisterView.vue
  src/views/parent/ParentCompetenciesSelection.vue
  src/views/parent/ParentDashboardHome.vue
  src/views/shared/CompetenceDialog.vue
  src/views/tutor/TutorDashboardHome.vue
  src/views/tutor/TutorExperts.vue
  src/views/tutor/TutorVenueInfo.vue
  src/views/user/ParentAchievements.vue
  src/views/user/ParentMyCompetencies.vue
  src/views/user/UserCompetencies.vue
  src/views/user/UserDashboardHome.vue
  tsconfig.tsbuildinfo
Labels: enhancement, ready for merge

#88 Feat | Admin users (parents) page
  src/components/AddChildForm.vue
  src/components/ChildrenList.vue
  src/components/ToastPopup.vue
  src/router/index.ts
  src/utils/FormatManager.ts
  src/views/admin/AdminUsers.vue
  src/views/auth/ForgotPasswordView.vue
  src/views/auth/LoginView.vue
  src/views/user/UserCompetencies.vue
  src/views/user/UserDashboardHome.vue
  tsconfig.tsbuildinfo
Labels: enhancement

#101 fix(admin): docs refresh after action fixed
  src/components/DocsToVerifyList.vue
  src/components/ToastPopup.vue
  src/views/admin/AdminDocuments.vue
Labels: enhancement

#107 Fix | competence update | Send null if age categories didn't change
  src/api/resolvers/competence/competence.resolver.ts
  src/api/resolvers/competence/dto/input/competence-update-input.dto.ts
  src/views/admin/AdminCompetencies.vue
  src/views/tutor/TutorCompetencies.vue
Labels: bug

#109 Fix | hide competence details
  src/views/shared/CompetenceDialog.vue
  src/views/user/UserCompetencies.vue
Labels: bug, enhancement
